/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esampark;

/**
 *
 * @author RAMAN DHALIWAL
 */
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
public class get_bill extends javax.swing.JInternalFrame {

    /**
     * Creates new form bill_display
     */
    public get_bill() {
        try {
            initComponents();
           DefaultTableModel m= new DefaultTableModel();
            jTable1.setModel(m);
            oprtr_props p= new oprtr_props();
            String[] col= new String[10];
            col[0]="cust_id"; col[1]="bill_no"; col[2]="mnth"; col[3]="units"; col[4]="bill_amount"; col[5]="due_date";
            col[6]="date_out"; col[7]="fine"; col[8]="total_amount"; col[9]="pay_status";
            String str="select * from custinfo2 where custid=?";
            Class.forName(p.getjdbcdriver());
            Connection con=DriverManager.getConnection(p.getdb(),p.getserver(),p.getdpass());
            PreparedStatement pst= con.prepareStatement(str);
            pst.setString(1, p.getcust_id());
            ResultSet res=pst.executeQuery();
            if(res.next())
            {
                m.setColumnIdentifiers(col);
                do{
                    Object[] row= new Object[col.length];
                    row[0]=res.getString(1);
                    row[1]=res.getInt(2);
                    row[2]=res.getString(3);
                    row[3]=res.getFloat(4);
                    row[4]=res.getFloat(5);
                    row[5]=res.getDate(6);
                    row[6]=res.getDate(7);
                    row[7]=res.getFloat(8);
                    row[8]=res.getFloat(9);
                    row[9]=res.getInt(10);
                    m.addRow(row);
                }while(res.next());
                jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

                    @Override
                    public void valueChanged(ListSelectionEvent e) {
                        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                       oprtr_props p= new oprtr_props();
                       //p.setcust_id(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                        p.setbill_no(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString()));
                        p.setmnth(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
                        p.setunits(Float.parseFloat(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString()));
                        p.setbill_amount(Float.parseFloat(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString()));
                        SimpleDateFormat formatter= new SimpleDateFormat("dd-MM-yyyy");
                        String due=formatter.format(jTable1.getValueAt(jTable1.getSelectedRow(), 5));
                        p.setdue_date(due);
                        SimpleDateFormat formatter1= new SimpleDateFormat("dd-MM-yyyy");
                        String out=formatter1.format(jTable1.getValueAt(jTable1.getSelectedRow(), 6));
                        p.setdate_out(out);
                        p.setfine(Float.parseFloat(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString()));
                        p.settotal(Float.parseFloat(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString()));
                        p.setstatus(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString()));
                    }
                });
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "no bills for this customer id");
            }
        } catch (Exception ex) {
            //Logger.getLogger(get_bill.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex.toString());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText(" BELOW ARE THE CORRESPONDING BILLS OF CUST_ID-");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(489, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
